Reformatting and migrate raster to terra
GeoScripting-WUR/VectorRaster pull request #20
Opened 2022-11-28 11:46 UTC by mvansluijs

@GreatEmerald

2022-11-30 22:01 UTC, GreatEmerald requested changes
Thanks, a few suggestions:

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
>  The GDAL library is well-documented (http://gdal.org/), but with a catch for R and Python programmers. The GDAL (and associated OGR) library and command line tools are all written in C and C++. Bindi
Did we explain what GDAL is up to this point?

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +Historically, the first package handling vectors in R was the *sp* package, and the first package handling rasters was the *raster* package. They had cross-integration so that you could perform opera
Numbering may change in the redesign, so better to say "previous tutorial"

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +> **Question:** Would you rather reproject a raster or a vector layer? Give two reasons why you would choose to reproject a raster or vector.
Why remove the number? Even if it's the only question, better to keep the number for future questions

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +Important functions are `st_read` and `st_write`. These are very powerful function that enable reading and writing simple features or layers from a file or data base.
```suggestion
Important functions are `st_read` and `st_write`. These are very powerful functions that enable reading and writing simple features or layers from a file or data base.
```

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +mapshot(mapview(water), url = 'mapview.html')
Maybe it's useful to first show what the standalone `mapview()` does, and then show how to save it to file?

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +writeVector(line, 'output/line.shp')
This makes the tutorial self-inconsistent, because at the top we state that we should always convert objects to the familiar formats if needed. So we can just demonstrate the use of `st_as_sf()` here.

2022-11-30 22:01 UTC, GreatEmerald commented on index.Rmd
> +We can plot the result as follows. However, note that the x axis does not really provide any indication of distance, as not all cells are equally distant from each other!
Well, the main point of this statement could rather be that the index number is not equivalent to a distance of 1 m. If you are not using an equidistant projection, of course there will also be a small difference between pixel sizes, but they may not be that big in the context of Belgium. Another reason may be if the line goes over a gap of NAs, or if you want to take the altitude into account when calculating the distance. But if we don't have the part about calculating distances here, then these are edge cases that may not be the most important point (also considering that not all students are from MGI). So perhaps this part could be rephrased to something like "because the distance between pixels is neither 1 m nor 1 km. If you go deeper into the issue, might also want to think about whether cells are all equally distant from one another." Or perhaps make it into a Question.

2022-12-01 09:16 UTC, mvansluijs commented on index.Rmd
>  The GDAL library is well-documented (http://gdal.org/), but with a catch for R and Python programmers. The GDAL (and associated OGR) library and command line tools are all written in C and C++. Bindi
Yes, in tutorial 2

2022-12-01 09:36 UTC, mvansluijs commented on index.Rmd
> +mapshot(mapview(water), url = 'mapview.html')
Yes, I guess that would make it more understandable

2022-12-01 09:36 UTC, mvansluijs commented on index.Rmd
> +We can plot the result as follows. However, note that the x axis does not really provide any indication of distance, as not all cells are equally distant from each other!
I've attempted to fit it into a question, as this tutorial only had one question so far.

2022-12-01 17:15 UTC, GreatEmerald commented on index.Rmd
>  The GDAL library is well-documented (http://gdal.org/), but with a catch for R and Python programmers. The GDAL (and associated OGR) library and command line tools are all written in C and C++. Bindi
OK!

2022-12-01 17:17 UTC, GreatEmerald approved these changes
Great, thanks!

2022-12-01 17:17 UTC, merged